version: "3"
services:
  # redis
  redis:
    container_name: redis_local_con-1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - redis-local-data:/data
    ports:
      - "6379:6379"
    networks:
      - net

volumes:
  redis-local-data:
networks:
  net:
